bioprogramme_production_complect:
    resource: "@BioprogrammeProductionBundle/Controller/ComplectController.php"
    type:     annotation

bioprogramme_production_building_block:
    resource: "@BioprogrammeProductionBundle/Controller/BuildingBlockController.php"
    type:     annotation

bioprogramme_branch_line:
    resource: "@BioprogrammeBranchBundle/Controller/LineController.php"
    type:     annotation

bioprogramme_production_machine_order:
    resource: "@BioprogrammeProductionBundle/Controller/MachineOrderController.php"
    type:     annotation

bioprogramme_production_machine:
    resource: "@BioprogrammeProductionBundle/Controller/MachineController.php"
    type:     annotation

bioprogramme_production_manufacturer:
    resource: "@BioprogrammeProductionBundle/Controller/ManufacturerController.php"
    type:     annotation

bioprogramme_production_category:
    resource: "@BioprogrammeProductionBundle/Controller/CategoryController.php"
    type:     annotation

bioprogramme_production_attribute:
    resource: "@BioprogrammeProductionBundle/Controller/AttributeController.php"
    type:     annotation

bioprogramme_production_attribute_group:
    resource: "@BioprogrammeProductionBundle/Controller/AttributeGroupController.php"
    type:     annotation

bioprogramme_marketing:
    resource: "@BioprogrammeMarketingBundle/Controller/"
    type:     annotation
    prefix:   /

bioprogramme_branch_building:
    resource: "@BioprogrammeBranchBundle/Controller/BuildingController.php"
    type:     annotation

bioprogramme_branch_base:
    resource: "@BioprogrammeBranchBundle/Controller/BaseController.php"
    type:     annotation

bioprogramme_branch_branch:
    resource: "@BioprogrammeBranchBundle/Controller/BranchController.php"
    type:     annotation

bioprogramme_production:
    resource: "@BioprogrammeProductionBundle/Controller/"
    type:     annotation
    prefix:   /

bioprogramme_branch:
    resource: "@BioprogrammeBranchBundle/Controller/"
    type:     annotation
    prefix:   /

bioprogramme_setting:
    resource: "@BioprogrammeSettingBundle/Controller/"
    type:     annotation
    prefix:   /

bioprogramme_account:
    resource: "@BioprogrammeAccountBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
