bioprogramme_setting:
    resource: "@BioprogrammeSettingBundle/Controller/"
    type:     annotation
    prefix:   /

bioprogramme_account:
    resource: "@BioprogrammeAccountBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
