parameters:
    bioprogramme_production.entity.attribute_group: 'BioprogrammeProductionBundle\Entity\AttributeGroup'
    bioprogramme_production.service.attribute_group_service: 'BioprogrammeProductionBundle\Service\AttributeGroupService'
    bioprogramme_production.entity.attribute: 'BioprogrammeProductionBundle\Entity\Attribute'
    bioprogramme_production.service.attribute_service: 'BioprogrammeProductionBundle\Service\AttributeService'
    bioprogramme_production.entity.category: 'BioprogrammeProductionBundle\Entity\Category'
    bioprogramme_production.service.category_service: 'BioprogrammeProductionBundle\Service\CategoryService'
    bioprogramme_production.entity.manufacturer: 'BioprogrammeProductionBundle\Entity\Manufacturer'
    bioprogramme_production.service.manufacturer_service: 'BioprogrammeProductionBundle\Service\ManufacturerService'
    bioprogramme_production.entity.machine: 'BioprogrammeProductionBundle\Entity\Machine'
    bioprogramme_production.service.machine_service: 'BioprogrammeProductionBundle\Service\MachineService'
    bioprogramme_production.entity.building_block: 'BioprogrammeProductionBundle\Entity\BuildingBlock'
    bioprogramme_production.service.building_block_service: 'BioprogrammeProductionBundle\Service\BuildingBlockService'
    bioprogramme_production.entity.complect: 'BioprogrammeProductionBundle\Entity\Complect'
    bioprogramme_production.service.complect_service: 'BioprogrammeProductionBundle\Service\ComplectService'
services:
    BioprogrammeProductionBundle\Form\MachineType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]
    BioprogrammeProductionBundle\Form\MachineAttributeReferenceType:
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']
        tags: [form.type]
    bioprogramme_production.attribute_group_manager:
        class: '%bioprogramme_production.service.attribute_group_service%'
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $container: '@service_container'
            $entity: '%bioprogramme_production.entity.attribute_group%'
    bioprogramme_production.attribute_manager:
        class: '%bioprogramme_production.service.attribute_service%'
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $container: '@service_container'
            $entity: '%bioprogramme_production.entity.attribute%'
    bioprogramme_production.category_manager:
        class: '%bioprogramme_production.service.category_service%'
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $container: '@service_container'
            $entity: '%bioprogramme_production.entity.category%'
    bioprogramme_production.manufacturer_manager:
        class: '%bioprogramme_production.service.manufacturer_service%'
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $container: '@service_container'
            $entity: '%bioprogramme_production.entity.manufacturer%'
    bioprogramme_production.machine_manager:
        class: '%bioprogramme_production.service.machine_service%'
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $container: '@service_container'
            $entity: '%bioprogramme_production.entity.machine%'
    bioprogramme_production.building_block_manager:
        class: '%bioprogramme_production.service.building_block_service%'
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $container: '@service_container'
            $entity: '%bioprogramme_production.entity.building_block%'
    bioprogramme_production.complect_manager:
        class: '%bioprogramme_production.service.complect_service%'
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $container: '@service_container'
            $entity: '%bioprogramme_production.entity.complect%'
