services:
    permission_listener:
        class: AppBundle\EventListener\PermissionListener
        arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']
#           $tokenStorage: '@security.token_storage'
#        tags:
#           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
    entity_owner_assignment_listener:
        class: AppBundle\EventListener\EntityOwnerAssignmentListener
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
#            - { name: doctrine.event_listener, event: preFlush }
    app.twig.extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
#        properties:
#            container: "@service_container"
        tags:
            - { name: twig.extension }
    app.image_manager:
        class: AppBundle\Service\ImageManagerService
        arguments:
            $container: '@service_container'
