<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * BuildingBlockAttributeReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingBlockAttributeReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
