<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * BuildingBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
