<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * ComplectDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplectDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
