<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * ComplectAttributeReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplectAttributeReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
