<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * ComplectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplectRepository extends \Doctrine\ORM\EntityRepository
{
}
