<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * MachineAttributeReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineAttributeReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
