<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * MachineOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
