<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * MachineManualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineManualRepository extends \Doctrine\ORM\EntityRepository
{
}
