<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * MachineOrderReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineOrderReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
