<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * MachineDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
