<?php

namespace BioprogrammeProductionBundle\Repository;

/**
 * MachineOrderHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineOrderHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
